### ISSUE TITLE
join with svbio table needs checking

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/survdat#1]
Results after joining survdat data with svbio table result in data being dropped.

eg. dogfish, SVSPP = 015 prior to 2001 are droppeed. should be records from 1992

data %>% dplyr::filter(YEAR < 2001, SVSPP =="015") %>% dplyr::distinct(YEAR)

**Comment by slucey** [comment]
Fixed.  Problem was with a piece of code that assigned catchsex for pre-FSCS records (<2001).  My old code used numbers while the new code was a character field.
