### ISSUE TITLE
Add more flexibility to data pull

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/survdat#18]
I was pulling some data for the SOE and realized that I don't need the entire time series every time nor did I need the length data which is the longest part of the data pull.  We should add some flexibility to the `get_survdat_data` function by allowing users to specify whether they want lengths and a filterByYear option.

**Comment by andybeet** [comment]
sounds good. Do you think we should do that before survdat's first release? or leave it for a future update?

**Comment by slucey** [comment]
I don't think this needs to hold anything up.  Should be a quick addition either way just won't have time until after the SOE workshop.

**Comment by andybeet** [comment]
I also think we should add to the list that is output
In addition to the data and the sql statements i think we should add

* the date of data pull
* the function call
