### ISSUE TITLE
Data pull output

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/survdat#26]
I also think we should add to the list that is output
In addition to the data and the sql statements i think we should add

* the date of data pull
* the function call

_Originally posted by @andybeet in https://github.com/NOAA-EDAB/survdat/issues/18#issuecomment-764873456_

**Comment by slucey** [comment]
Didn't want to lose this thought when my pull request closes the other issue.

**Comment by andybeet** [comment]
addressed in pull request [#19](https://github.com/NOAA-EDAB/survdat/pull/19)
