### ISSUE TITLE
Change function name

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/survdat#8]
I'd like to change the name of the function `swept_area_biomass` to `calc_swept_area` to avoid confusion with the embedded function `swept_area`.  I also want to make a companion function `calc_stratified_mean`.

**Comment by andybeet** [comment]
Yeah sounds like a good idea to change the name. Regarding the `calc_stratified_mean` how would that be different from `strat_mean`?

**Comment by slucey** [comment]
It would function like `strat_mean_biomass` in that it would run all the steps necessary to generate a stratified mean but stop one step shorter (no `swept_area` call).
